<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/05/23 16:10:54

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=users',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
